# Generated by Django 5.2.4 on 2025-08-20 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
