# Generated by Django 5.2 on 2025-10-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_book_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending_form', 'Pending Form'), ('initiated', 'Initiated'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], default='initiated', max_length=20),
        ),
    ]
