# Generated by Django 5.2.4 on 2025-09-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usersession_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
