# Generated by Django 5.2 on 2025-11-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='device_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device_fingerprint',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_bb1b83_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['device_fingerprint'], name='user_sessio_device__4dc2be_idx'),
        ),
    ]
