# Generated by Django 5.2 on 2025-11-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersession_device_info_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usersession',
            name='user_sessio_user_id_bb1b83_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersession',
            name='user_sessio_device__4dc2be_idx',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='device_info',
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device_fingerprint',
            field=models.CharField(max_length=255),
        ),
    ]
