# Generated by Django 5.2.4 on 2025-09-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_paid',
        ),
    ]
