# Generated by Django 5.2 on 2025-11-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usersession_user_sessio_user_id_bb1b83_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='device_fingerprint',
        ),
    ]
