# Generated by Django 5.2 on 2025-11-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_usersession_device_fingerprint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
