# Generated by Django 5.2.4 on 2025-07-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingquestion',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
