# Generated by Django 5.2.4 on 2025-07-31 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_readingquestion_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingquestion',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_questions', to='questions.book'),
        ),
    ]
