# Generated by Django 5.2.4 on 2025-07-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_readingquestion_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingquestion',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
