# Generated by Django 5.2.4 on 2025-07-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_matchingquestion_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='truefalsequestion',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
