# Generated by Django 5.2.4 on 2025-08-12 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_truefalsequestion_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingpassage',
            name='book',
        ),
        migrations.RemoveField(
            model_name='readingquestion',
            name='passage',
        ),
        migrations.RemoveField(
            model_name='readingquestion',
            name='book',
        ),
        migrations.CreateModel(
            name='ReadingComprehension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('question_text', models.TextField()),
                ('title', models.CharField(max_length=255, verbose_name='عنوان القطعة')),
                ('content', models.TextField(verbose_name='محتوى القطعة')),
                ('questions_data', models.JSONField(default=list, help_text='قائمة بالأسئلة والاختيارات والإجابات الصحيحة', verbose_name='الأسئلة والإجابات')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_comprehensions', to='questions.book')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ReadingChoice',
        ),
        migrations.DeleteModel(
            name='ReadingPassage',
        ),
        migrations.DeleteModel(
            name='ReadingQuestion',
        ),
    ]
